
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    # extra_hosts:
    #   - "swarm-manager:172.31.224.1"
    # networks:
    #   - internal
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.jenkins.rule=${JENKINS_HOST_RULE}
    #   - traefik.http.routers.jenkins.tls.certresolver=letsencrypt
    #   - traefik.http.services.jenkins.loadbalancer.server.port=8080

# networks:
#   internal:
#     external: true